version: "3.9"

services:
  web:
    image: yvantchuente/cadexsa
    container_name: cadexsa-web
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
    labels:
      description: "Cadexsa's official web site"
    networks:
      - front-end
      - back-end
    volumes:
      - type: volume
        source: app-logs
        target: /var/www/html/logs
  db:
    image: mariadb
    container_name: cadexsa-db
    restart: always
    ports:
      - target: 3306
        published: 3306
    networks:
      - back-end
    env_file: .env
    environment:
      MARIADB_DATABASE: cadexsa_db
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

networks:
  front-end:
  back-end:

volumes:
  app-logs:
  mysql-data:
